# Generated by Django 4.0.6 on 2022-08-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('tmef', models.TextField(null=True)),
                ('wf', models.TextField(null=True)),
                ('tmn', models.IntegerField(default=0)),
                ('tmx', models.IntegerField(default=0)),
            ],
        ),
    ]
